Fixed some mistakes and added some embedded hyperlinks
cosmo-epfl/kernel-tutorials pull request #20
Opened 2020-10-13 15:16 UTC by PKGuo

I fixed some mistakes and added some hyperlinks in 0_Foreword.ipynb and 1_LinearMethods.ipynb. 

This is my first time opening a pull request,  so I would just like to try to modify it a little bit.

2020-10-13 15:33 UTC, rosecers requested changes
Looks pretty good! I can see quickly merging this in with @bhelfrecht, @Luthaf, or @ceriottm's approvals.

2020-10-13 15:33 UTC, rosecers commented on notebooks/0_Foreword.ipynb
> +    "The atom-centred environments are represented in terms of 2 and 3-body correlations, described by the [SOAP](https://doi.org/10.1039/c6cp00415f) power spectrum, and can be computed using the `li
```suggestion
    "The atom-centred environments are represented in terms of 2 and 3-body correlations, described by the [SOAP](https://doi.org/10.1063/1.5090481) power spectrum, and can be computed using the `librascal` library, following the procedure in  [Importing Data](X_ImportingData.ipynb). For ease of use, pre-computed features can be downloaded from [here](https://www.dropbox.com/s/itokckbbkvxaqsk/precomputed.npz?dl=0). The file `precomputed.npz` should be copied to the `datasets/` folder."
```

It may be better to use Felix and Michael's paper, as the notation is clearer and more similar

2020-10-13 15:33 UTC, rosecers commented on notebooks/0_Foreword.ipynb
> +   "version": "3.7.4"
```suggestion
   "version": "3.6.9"
```

Make sure not to include Python version lines in PRs.

2020-10-13 15:33 UTC, rosecers commented on notebooks/1_LinearMethods.ipynb
> +   "version": "3.7.4"
Same as above.
```suggestion
   "version": "3.7.3"
```

2020-10-13 15:38 UTC, Luthaf commented on notebooks/0_Foreword.ipynb
> +   "version": "3.7.4"
This should be automated in some way, having to deal with it for each PR is a bit of a pain =) Does `nbstrip` handles this?

2020-10-13 15:39 UTC, Luthaf commented
This looks good to me!

2020-10-13 16:54 UTC, PKGuo commented on notebooks/0_Foreword.ipynb
> +   "version": "3.7.4"
I have tried ` nbstrip` , but it doesn't handle this. So I modified it manually.

2020-10-13 17:10 UTC, PKGuo commented
I changed the reference and manually modified the Python version lines. Anything else?

2020-10-14 07:23 UTC, rosecers approved these changes

2020-10-14 07:23 UTC, merged