Sklearnify NB2
cosmo-epfl/kernel-tutorials pull request #28
Opened 2020-11-18 08:42 UTC by PKGuo

Replace some utility classes in `2_PrincipalCovariatesRegression.ipynb` with appropriate `sklearn` classes and modified corresponding texts.

2020-11-18 10:57 UTC, rosecers commented on notebooks/2_PrincipalCovariatesRegression.ipynb
> +    "from utilities.classes import PCovR # to be replaced with scalers from skcosmo\n",
did you mean to say scalers here?

2020-11-18 13:08 UTC, rosecers requested changes
just a few typos to fix

2020-11-18 13:26 UTC, PKGuo commented on notebooks/2_PrincipalCovariatesRegression.ipynb
> +    "from utilities.classes import PCovR # to be replaced with scalers from skcosmo\n",
Sorry. It should be "to be replaced with the class from skcosmo".

2020-11-20 14:06 UTC, rosecers approved these changes

2020-11-20 14:06 UTC, merged